use MagazinAlimentar

-- Solution: SET TRANSACTION ISOLATION LEVEL TO READ COMMITTED

select *from Produs

SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
SELECT *FROM Produs
WAITFOR DELAY '00:00:10'
SELECT *FROM Produs
COMMIT TRAN

select *from Produs
