use MagazinAlimentar
go 

-- SOLUTION :
SELECT *FROM Produs

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
SELECT *FROM Produs
WAITFOR DELAY '00:00:10'
SELECT *FROM Produs
COMMIT TRAN

SELECT *FROM Produs